### ISSUE TITLE
Apporter une modification sur l'API mission transition (une info pourrait nous servir, cf. Aides Territoires)

### ISSUE THREAD

**Issue by AmineKheldouni** [dataforgoodfr/offseason_missiontransition_categorisation#1]

**Comment by Linkinou** [comment]
@AmineKheldouni te souviens-tu de l'info en question qui n'était pas remontée par l'API ?

**Comment by AmineKheldouni** [comment]
Malheureusement non. Je te dirai si je retrouve. Ce n'est pas un point bloquant et on retrouvera sans doute en mergeant les deux jeux de données.
