### ISSUE TITLE
Nettoyer le fichier de données

### ISSUE THREAD

**Issue by AmineKheldouni** [dataforgoodfr/offseason_missiontransition_categorisation#4]

**Comment by Linkinou** [comment]
Work in progress, je suis en train de travailler sur la v4 du site qui comprend un nettoyage de la base de donnée des champs non utilisés.

Déploiement prévu pour le lundi 29.

**Comment by AmineKheldouni** [comment]
Parfait, merci @Linkinou !
On essaye de faire le même exercice dans l'équipe et de brainstormer les approches d'apprentissage envisagées pour discuter de cela avec toi lors d'un prochain meeting.
