### ISSUE TITLE
Convenir d'une liste figée et révisée de thématiques/sous thématiques

### ISSUE THREAD

**Issue by AmineKheldouni** [dataforgoodfr/offseason_missiontransition_categorisation#8]

**Comment by Linkinou** [comment]
Bonjour @AmineKheldouni 

Navré je ne vois cela que maintenant, est-ce que la liste actuellement présente chez MTE suffit ?
https://mission-transition-ecologique.beta.gouv.fr/api/environmental-topics

**Comment by AmineKheldouni** [comment]
Super c'est exactement ce que je cherchais ! 👍
